example api test

diff --git a/.github/workflows/CI-tests.yml b/.github/workflows/CI-tests.yml
--- a/.github/workflows/CI-tests.yml
+++ b/.github/workflows/CI-tests.yml
@@ -21,7 +21,7 @@ jobs:
     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
-        node-version: '16'
+        node-version: '18'
 
     # Step 3: Install dependencies
     - name: Install dependencies
@@ -36,14 +36,10 @@ jobs:
       id: playwright_tests
       continue-on-error: true
       run: |
-        PLAYWRIGHT_JSON_OUTPUT_FILE=results.json npx playwright test --reporter=json
-        exit_code=$?
+        exit_code=0
+        PLAYWRIGHT_JSON_OUTPUT_FILE=results.json npx playwright test --reporter=json || exit_code=$?
 
-        if [ $exit_code -ne 0 ]; then
-          echo "TEST_FAILED=true" >> $GITHUB_OUTPUT
-        else
-          echo "TEST_FAILED=false" >> $GITHUB_OUTPUT
-        fi
+        echo "TEST_FAILED=$exit_code" >> $GITHUB_OUTPUT
 
         exit $exit_code
 
@@ -61,13 +57,11 @@ jobs:
 
     - name: Upload HTML report as artifact
       uses: actions/upload-artifact@v4
+      continue-on-error: true
       with:
         name: playwright-report
         path: playwright-report/**
 
     - name: Fail The Workflow if tests failed
-      if: ${{ steps.playwright_tests.TEST_FAILED == 'true'}}
-      uses: actions/github-script@v3
-      with:
-        script: |
-          core.setFailed('Some Tests Failed')
+      if: ${{ steps.playwright_tests.outputs.TEST_FAILED  != 0 }}
+      run: exit 1
